modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
authors="Niko"

[[mods]]
modId="ragnarok"
version="1.0.0"
displayName="Ragnarok"
description='''Ragnarokへようこそ!'''

[[dependencies.ragnarok]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.ragnarok]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.ragnarok]]
modId="geckolib"
mandatory=true
versionRange="[4.4.4,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.ragnarok]]
modId="curios"
mandatory=true
versionRange="[4.4.4,)"
ordering="BEFORE"
side="BOTH"
